[theme]
# Primary accent color for interactive elements
primaryColor = "#FF4B4B"

# Background color for the main content area
backgroundColor = "#FFFFFF"

# Background color used for the sidebar and most interactive widgets
secondaryBackgroundColor = "#F0F2F6"

# Color used for almost all text
textColor = "#262730"

# Font family for all text in the app, except code blocks
font = "sans serif"

[server]
# If false, will attempt to open a browser window on start
headless = true

# Automatically rerun script when files change
runOnSave = true

# Max size, in megabytes, for files uploaded with the file_uploader
maxUploadSize = 200

[browser]
# Internet address where users should point their browsers in order to connect to the app
serverAddress = "0.0.0.0"

# Port where the server will listen for browser connections
serverPort = 8501 